### ISSUE TITLE
Error with guidescan enumerate

### ISSUE THREAD

**Issue by Lukas-1** [pritykinlab/guidescan-cli#13]
Hi,

I'm excited to try out the new version of GuideScan, but I've been getting the following error:

guidescan enumerate ncbi-genomes-2022-12-21/hg38 -f Input_for_GuideScan2/input.csv -o Output_from_GuideScan2/output.csv
[guidescan2] [info] Loading genome index at "ncbi-genomes-2022-12-21/hg38".
[guidescan2] [info] Successfully loaded genome index.
[guidescan2] [info] Loading kmers.
[guidescan2] [info] Read in 40664 kmer(s).
terminate called after throwing an instance of 'std::out_of_range'
  what():  basic_string::substr: __pos (which is 1) > this->size() (which is 0)
Aborted (core dumped)

I downloaded the RefSeq .fna file for hg38 from this page https://www.ncbi.nlm.nih.gov/assembly/GCF_000001405.26/, and indexing seemed to complete successfully. Do you know what might be causing the issue?

Thanks,
Lukas

**Comment by vineetbansal** [comment]
I think it might be that you don't have anything in the PAM column in your `input.csv`? We noticed this issue recently and are about to patch it up.

**Comment by Lukas-1** [comment]
That fixed it! Thanks a lot for the quick reply, and for creating and maintaining this great tool!

**Comment by vineetbansal** [comment]
Great - let me close this issue, but we'll fix the underlying issue in the next couple of days in `guidescan` which should make it work even in the absence of any PAMs.
