### ISSUE TITLE
Using a 5' PAM for enumeration

### ISSUE THREAD

**Issue by ericmalekos** [pritykinlab/guidescan-cli#27]
Thank you for the great tool. 
Is there anyway to enumerate off-targets under the assumption that that the PAM is 5' to the protospacer?
For Cas12A for example the targets are 5' - PAM (TTTV) - protospacer - 3'

**Comment by schmidt73** [comment]
Sorry for the delay, a simple way to do this is to append the 5' PAM to the input kmers.

**Comment by ericmalekos** [comment]
Can you provide example entries? 
Say for a 5'-TTTV-protospacer-3' for Cas12A?
