### ISSUE TITLE
confusing header of decode_database.py output in succinct mode

### ISSUE THREAD

**Issue by mzhibo** [pritykinlab/guidescan-cli#3]
Hi,
When I run the decode-database.py in succinct mode on the example data, I saw the report have header names including: distance-1-mismatch, distance-2-mismatch,distance-2-mismatch,distance-3-mismatch.
There are two distance-2-mismatch, Should it be distance-0 to distance-3 and above instead? Where distance-0 is perfect match.
Thanks for clarifying.
Zhibo

**Comment by schmidt73** [comment]
Fixed the issue. You were correct and thanks for the report.
