### ISSUE TITLE
Paired-guide sgRNA design tutorial ?

### ISSUE THREAD

**Issue by ahy1221** [pritykinlab/guidescan-cli#5]
Dear developers,

Thank you for providing this useful and effecient tools for sgRNA design !
It seems that the guidescan2 could output paired-guide sgRNAs for target genes according to the fig 1 in the manuscript. 
![图片](https://user-images.githubusercontent.com/27558284/184124247-317f30ee-35fa-495e-a5c9-965e8cca068b.png)

However I can not find any option for such output in the websites and in the manual of guidescan-cli.  I was wondering that could you provide tutorial for this feature ?

Best,

Yao

**Comment by schmidt73** [comment]
This feature is provided by the website via the "flanking" option which searches for guides to the left and right ends of your genomic regions.

![image](https://user-images.githubusercontent.com/6162705/184136163-1528629d-784e-430a-a214-3ba9de7b0516.png)

For doing this via the command line tool, it would require some manual effort. Specifically, one would need to transform their genomic regions to a pair of genomic regions representing the flanking regions and then send those through Guidescan2. This shouldn't be too difficult, but I think it would be a good addition to spell this out more completely in the manual.

I'll keep the issue open until this is done, but until then feel free to email me privately to discuss.
